name: Deploy en Preproducción

on:
  push:
    branches:
      - preproduccion 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v3  

    - name: Configurar Node.js
      uses: actions/setup-node@v3  
      with:
        node-version: '16'  

    - name: Instalar dependencias
      run: npm install

    - name: Actualizar versión y generar changelog
      run: npm run release
    
    - name: Configurar identidad de Git
      run: |
      git config --local user.name "GitHub Actions"
      git config --local user.email "actions@github.com"

    - name: Hacer commit de los cambios de versionado y changelog
      run: |
      git add .
      git commit -m "chore(release): actualización de versión automática"
      git push origin preproduccion --follow-tags

    - name: Ejecutar pruebas
      run: npm test

    - name: Desplegar en preproducción
      run: |
        echo "Desplegando aplicación en preproducción"
        # Aquí iría el comando para desplegar en tu servidor de preproducción
