name: Deploy en Preproducción

on:
  push:
    branches:
      - preproduccion

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v3  

    - name: Configurar Node.js
      uses: actions/setup-node@v3  
      with:
        node-version: '16'  

    - name: Instalar dependencias
      run: npm install

    - name: Configurar identidad de Git
      run: |
        git config --global user.name "${{ secrets.GIT_USER_NAME }}"
        git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"

    - name: Actualizar versión y generar changelog
      run: npm run release

    - name: Hacer commit de los cambios de versionado y changelog
      run: |
        git add .
        git commit -m "chore(release): actualización de versión automática"
        git push https://x-access-token:${{ secrets.ACCESS_TOKEN }}@github.com/impacevanend/Preproduction-Release-Automation.git preproduccion --follow-tags

    - name: Ejecutar pruebas
      run: npm test

    - name: Desplegar en preproducción
      run: |
        echo "Desplegando aplicación en preproducción"
        # Comando para desplegar en tu servidor de preproducción
