name: CI/CD Pipeline

on:
  push:
    branches:
      - preproduccion
  pull_request:
    branches:
      - preproduccion

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v2

    - name: Configurar Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Instalar dependencias
      run: npm install


    - name: Ejecutar pruebas
      run: npm test

    - name: Desplegar en preproducción
      run: |
        echo "Desplegando en preproducción..."
        # Comandos necesarios para el despliegue

    - name: Forzar despliegue si fallan los pasos previos
      run: |
        echo "Intentando forzar el despliegue."
        git push --force origin preproduccion --follow-tags
