name: Deploy en Preproducción

on:
  push:
    branches:
      - preproducción  # Aquí configuras que el flujo se ejecute al hacer push a la rama "preproducción"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v2

    - name: Configurar Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Instalar dependencias
      run: npm install

    - name: Ejecutar pruebas
      run: npm test

    - name: Desplegar en preproducción
      run: |
        echo "Desplegando aplicación en preproducción"
        # Aquí iría el comando para desplegar en tu servidor de preproducción
