name: Deploy en Preproducción

on:
  push:
    branches:
      - preproduccion

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v3

    - name: Configurar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Instalar dependencias
      run: npm install

    - name: Verificar valores secretos
      run: |
        echo "Usuario: ${{ secrets.GIT_USER_NAME }}"
        echo "Email: ${{ secrets.GIT_USER_EMAIL }}"

    - name: Actualizar versión y generar changelog
      run: npm run release
    
    - name: Configurar identidad de Git
      run: |
        git config --local user.name "${{ secrets.GIT_USER_NAME }}"
        git config --local user.email "${{ secrets.GIT_USER_EMAIL }}"

    - name: Hacer commit de los cambios de versionado y changelog
      run: |
        git add .
        git commit -m "chore(release): actualización de versión automática"
        git push origin preproduccion --follow-tags

    - name: Ejecutar pruebas
      run: npm test

    - name: Desplegar en preproducción
      run: |
        echo "Desplegando aplicación en preproducción"
