name: Deploy en Preproducción

on:
  push:
    branches:
      - preproduccion

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v3

    - name: Configurar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Instalar dependencias
      run: npm install

    - name: Actualizar versión y generar changelog
      run: npm run release

    # Omitir commit local y hacer push directo usando el token
    - name: Push cambios con token de autenticación
      env:
        TOKEN: ${{ secrets.ACCESS_TOKEN }}
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "chore(release): actualización de versión automática"
        git push https://$TOKEN@github.com/tu_usuario/tu_repositorio.git HEAD:preproduccion --follow-tags

    - name: Ejecutar pruebas
      run: npm test

    - name: Desplegar en preproducción
      run: |
        echo "Desplegando aplicación en preproducción"
